### ISSUE TITLE
コメント: DRYについて…

### ISSUE THREAD

**Issue by blmd-niz** [sanaig/SWDrill#1]
まとめていただきありがとうございました。
ソフトウェアの面についてまとめていただいたのですが、実はそれ以外にも基本的にDRYに仕事を進めたい考えがあります。
これまで、下記のような仕事の進め方が見受けられました。
a. 作業を十分定義せず、同じ作業を繰り返す。例) 配線にマーキングせず、再配線のたびにどれを繋げばよいか調べている。
b. 説明を十分に明文化しないため、毎回口頭で説明している。
一度行った仕事は再利用可能な状態にまとめていく進め方を基本として頂ければ、間違いないかと思います。
(ご確認後クローズして下さい)

**Comment by sanaig** [comment]
御確認頂きましてありがとうございます。
御指摘頂いた2点を元に、仕事においてもDRYに進められるよう意識していきます。
